services:
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - anclora-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      - VITE_API_URL=http://localhost:${NGINX_PORT}/api
      - VITE_SUPABASE_URL=https://kehpwxdkpdxapfxwhfwn.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaHB3eGRrcGR4YXBmeHdoZnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTU4NzgsImV4cCI6MjA2Njg3MTg3OH0.K8cs9gQWc1P6Js4q8H88QQyJ4Nh4CVbV4JW70QpjOlM
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - anclora-network

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_PORT=${BACKEND_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - RESULTS_FOLDER=${RESULTS_FOLDER}
      - CONVERSION_TIMEOUT=${CONVERSION_TIMEOUT}
      - SUPABASE_URL=https://kehpwxdkpdxapfxwhfwn.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaHB3eGRrcGR4YXBmeHdoZnduIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTI5NTg3OCwiZXhwIjoyMDY2ODcxODc4fQ.ZRYM0R46-qDniCRbLsVlbwRDP0Ra087eOlpvT9FlGHQ
    volumes:
      - ./backend:/app
      - uploads:/app/${UPLOAD_FOLDER}
      - results:/app/${RESULTS_FOLDER}
    depends_on:
      redis:
        condition: service_started
    networks:
      - anclora-network

  worker:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - RESULTS_FOLDER=${RESULTS_FOLDER}
      - CONVERSION_TIMEOUT=${CONVERSION_TIMEOUT}
      - WORKER_METRICS_PORT=${WORKER_METRICS_PORT}
      - SUPABASE_URL=https://kehpwxdkpdxapfxwhfwn.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaHB3eGRrcGR4YXBmeHdoZnduIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTI5NTg3OCwiZXhwIjoyMDY2ODcxODc4fQ.ZRYM0R46-qDniCRbLsVlbwRDP0Ra087eOlpvT9FlGHQ
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    volumes:
      - ./backend:/app
      - uploads:/app/${UPLOAD_FOLDER}
      - results:/app/${RESULTS_FOLDER}
    depends_on:
      redis:
        condition: service_started
    networks:
      - anclora-network
    ports:
      - "${WORKER_METRICS_PORT}:${WORKER_METRICS_PORT}"

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - anclora-network

# PostgreSQL removed - now using Supabase

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
      - worker
    networks:
      - anclora-network

  grafana:
    image: grafana/grafana
    ports:
      - "3004:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - anclora-network

volumes:
  uploads:
  results:
  redis_data:
  grafana_data:

networks:
  anclora-network:
