services:
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - anclora-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      - REACT_APP_API_URL=http://localhost:${NGINX_PORT}/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - anclora-network

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_PORT=${BACKEND_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - RESULTS_FOLDER=${RESULTS_FOLDER}
      - CONVERSION_TIMEOUT=${CONVERSION_TIMEOUT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
      - uploads:/app/${UPLOAD_FOLDER}
      - results:/app/${RESULTS_FOLDER}
    depends_on:
<<<<<<< HEAD
      - redis
      - db
=======
      redis:
        condition: service_started
      db:
        condition: service_healthy
>>>>>>> 5f593d68be5c1d46de58f07a789fc6777c63a20f
    networks:
      - anclora-network

  worker:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - RESULTS_FOLDER=${RESULTS_FOLDER}
      - CONVERSION_TIMEOUT=${CONVERSION_TIMEOUT}
      - DATABASE_URL=${DATABASE_URL}
      - WORKER_METRICS_PORT=${WORKER_METRICS_PORT}
    volumes:
      - ./backend:/app
      - uploads:/app/${UPLOAD_FOLDER}
      - results:/app/${RESULTS_FOLDER}
    depends_on:
      - redis
      - db
    networks:
      - anclora-network
    ports:
      - "${WORKER_METRICS_PORT}:${WORKER_METRICS_PORT}"

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - anclora-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - anclora-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
      - worker
    networks:
      - anclora-network

  grafana:
    image: grafana/grafana
    ports:
      - "3004:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - anclora-network

volumes:
  uploads:
  results:
  redis_data:
  postgres_data:
  grafana_data:

networks:
  anclora-network: