FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Construir para producción
RUN npm run build

EXPOSE 5178

# Usar modo preview para producción
CMD ["npm", "run", "serve", "--", "--host", "0.0.0.0", "--port", "5178"]
