global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5175']
  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:8001']
